### ISSUE TITLE
[Bug] Segmentation fault or another error

### ISSUE THREAD

**Issue by Zedzs** [slow/nitro-sniper#85] opened 2021-05-03 00:15 UTC
When executing, I'm always either getting a "Segmentation fault" error or sometimes an error like in the picture

Already reinstalled nodejs and the sniper and made sure the config is not broken.
![cmd_fcYrYjBnU7](https://user-images.githubusercontent.com/83560764/116832518-5e08d700-abb5-11eb-8756-c2eeeead18f0.png)

**Comment by slow** [comment] 2021-05-03 15:23
You're most likely using an incompatible node version.

**Comment by slow** [comment] 2021-05-03 15:37
If anyone can reproduce please list the following:
`Node.js Version`
`Platform (linux/windows/mac)`

**Comment by UltraHQ** [comment] 2021-05-03 15:44
> If anyone can reproduce please list the following:
> `Node.js Version`
> `Platform (linux/windows/mac)`

Node.js version 14.16.1 (16.0.0 does not work at all)
Platform: Linux - Debian 10

**Comment by InimicalPart** [comment] 2021-06-07 14:39
@Zedzs What node version are you using?

I was unable to reproduce this issue on versions:
- 16.3.0
- 16.2.0
- 16.1.0
- 16.0.0
- 15.14.0
- 15.13.0
- 15.12.0
- 15.11.0
- 15.10.0
- 15.9.0
- 15.8.0
- 15.7.0
- 15.6.0
- 15.5.1
- 15.5.0
- 15.4.0
- 15.3.0
- 15.2.1
- 15.2.0
- 15.1.0
- 15.0.1
- 13.13.0
- 12.16.2
- 11.15.0
- 10.20.1
- 9.11.2
- 8.17.0
- 7.10.1
- 6.17.1
- 5.12.0
- 4.9.1
- 0.12.18

**Comment by slow** [comment] 2021-06-07 17:20
As no other people have had this issue for a while, i'll close this. If anyone faces this issue please open an issue.

**Closed by slow** 2021-06-07 17:20 UTC
