### ISSUE TITLE
[Feature Request] To Snipe More Giveaway Bots

### ISSUE THREAD

**Issue by TheJoaqun** [slow/nitro-sniper#273] opened 2021-10-10 23:27 UTC
### Is your feature request related to a problem?

No...

### Describe the solution you'd like

The Sniper is usseful to snipe others bots (giveaways).

### How will this be beneficial to the sniper

It would be beneficial to the sniper and the users, Why?, Because The Sniper Can Snipe More GIveaway COnetnts for others bots

### Please provide an example of usage of this feature

To Snipe In Differents Bots or Message giveaway. That In Line 38 code to snipe giveaway that looks like this   
`if (msg.content.includes('**GIVEAWAY**') && msg.content.includes(':yay:')) {`
we can change the code to ``if (msg.content.includes('**GIVEAWAY**') || msg.content.includes(':yay:') || msg.content.includes('Hosted By')) {``

of more like this Names That Includes Hosted etc..

**Comment by slow** [comment] 2021-10-17 11:55
Duplicate of #152

**Closed by slow** 2021-10-17 11:55 UTC
Labels: duplicate, enhancement
